version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      -"80:80"
    volumes:
      - ./app:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 80"
    depends_on:
      - db

  db:
    image: library/postgres:11-alpine
    environment:
      - POSTGRES_DB: fastdb
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: pass
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432

volumes:
  postgres_data:
