version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "uvicorn api.main:app --host 0.0.0.0"
    depends_on:
      - db

  db:
    image: library/postgres:11-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432

volumes:
  postgres_data:
